### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by JesseEmond** [JesseEmond/csgains#2]
- [x] run default miner/ca server
- [x] implement in C++
- [x] optimize C++ version
- [x] multithreaded (w/ early stopping)
- [x] try with their server with local miner
- [x] comment why we still have the python code running at the end
- [x] cleanup code
